# Generated by Django 6.0.2 on 2026-02-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_name_product_title_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
